### PR TITLE
Add some new app manifests

### PR DESCRIPTION
**Pull request by rashil2000**
The fixes to the main bucket repo take literal months to get merged for no apparent reason, so I'm contributing them here. 

Hope that's okay :)

### CODE REVIEW

**Review by naderi — COMMENTED** [review]
macchina: Add manifest.

**Review by naderi — COMMENTED** [review]
Add manifest

**Comment by rashil2000** [comment]
Hi, I'm not sure I follow, did I miss something?

**Comment by naderi** [comment]
No that was something for myself 😊

**Comment by rashil2000** [comment]
Thank you very much! :)

**Pull request merged**
