### PR TITLE
Sync with official buckets (5)

### PR DESCRIPTION
**Pull request by rashil2000**
I have added these apps in the official buckets.

**Main**

mosh-client - https://github.com/ScoopInstaller/Main/blob/master/bucket/mosh-client.json

**Versions**

neovim - https://github.com/ScoopInstaller/Versions/blob/master/bucket/neovim-bare.json

neovim-nightly - https://github.com/ScoopInstaller/Versions/blob/master/bucket/neovim-bare-nightly.json

### CODE REVIEW

**Review by naderi — COMMENTED** [review]
I don't want to add the versions bucket to my scoop installation, so I'll leave the files as they are.

**Comment by naderi** [comment]
Hi @rashil2000 
thank you for the update but I don't want to add the versions bucket to my scoop installation, so I'll leave the files as they are.
"mosh-client" is deleted.

**Comment by rashil2000** [comment]
Btw Neovim is also present in Main bucket https://github.com/ScoopInstaller/Main/blob/master/bucket/neovim.json

**Comment by naderi** [comment]
Deleted as well.

**Comment by naderi** [comment]
@rashil2000 I've now added the versions bucket and deleted all manifests you mentioned above. Thank you again for PR.

**Comment by rashil2000** [comment]
Thanks for the update. 

Even I was hesitant to add the Versions bucket till a few days ago. But we spent a good amount of time reorganizing manifests in all official buckets and performing cleanup etc. to make them more consistent. So now I use Versions bucket too.

**Comment by naderi** [comment]
You're welcome!
Btw what is "Shovel" created by "Ash258" (https://github.com/Ash258/Scoop-Core)?
Today I found it by accident.

**Comment by rashil2000** [comment]
Shovel is a fork (not official) of Scoop by someone. It has diverged a lot from upstream (with both new features and incompatibilities).

**Pull request closed without merging**
