### PR TITLE
Sync with Main bucket (3)

### PR DESCRIPTION
**Pull request by rashil2000**

### CODE REVIEW

**Review by naderi — APPROVED** [review]
Sync with main bucket.

**Comment by naderi** [comment]
@rashil2000 Why you delete some manifests, which are not exist in any other standard buckets? (e.g. "dotter" or "ag-win")

**Comment by rashil2000** [comment]
dotter and ag (ag-win) both are there in Main buckets

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/ag.json
https://github.com/ScoopInstaller/Main/blob/master/bucket/dotter.json

**Comment by rashil2000** [comment]
I removed only those manifests which are also there in Main (to avoid duplication, as mentioned in #26)

**Comment by naderi** [comment]
Ah, OK! Sorry 😐
Weirdly enough I can't find them on my computer (no json file and nothing with "scoop find xyz"), do you have any idea what it could be? I run the command "scoop update *" every single day.

**Comment by rashil2000** [comment]
Can you navigate to the bucket directory (most likely C:\\Users\\username\\scoop\\buckets\\main) and run `git log` there? It will show you the recent commits and you can check when it was last updated.

**Pull request merged**
